config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #
  match 'active'  => 'admin/sessions#active',  via: :get
  match 'timeout' => 'admin/sessions#timeout', via: :get

  namespace :admin do
    get '/' => 'users#dashboard'

    resources :users do
      collection do
        get :dashboard
      end
    end

    resources :sessions do
      collection do
        get :login
        post :login_attempt
        get :logout
      end
    end
    resources :orders, only: [:index, :show, :update, :create, :new, :edit] do
      collection do
        get :download_order
        put :tracking
        get :tracking_modal
        get :paid
        get :download_excel
        get :order_detail_excel
        put :add_delivery
      end
    end
    resources :roles
    resources :permissions
    resources :product_stock do
      collection do
        get :download_excel
      end
    end
    resources :customers do
      collection do
        put :verify
        get :download_excel
        post :import
      end
    end
    #resources :customers_imports, only: [:new, :create]
    resources :product_offers do
      collection do
        post :upload_offer_image
      end
    end

    resources :products, only: [:index, :show, :update, :create, :new, :edit] do
      collection do
        post :upload_product_image
        get :download_excel
        post :import
      end
    end

    resources :product_divisions, only: [:index, :show, :update, :create, :edit, :new] do
      collection do
        post :upload_division_image
      end
    end

    resources :product_sections, only: [:index, :show, :update, :create, :edit, :new]  do
      collection do
        post :upload_section_image
      end
    end

    resources :product_departments, only: [:index, :show, :update, :create, :edit, :new]

    resources :coupons do
      collection do
        put :redeem_coupon
        post :generate_coupons
      end
    end

    resources :debtors, only: [:index, :show] do
      collection do
        get :add_entry
        post :create_entry
        post :upload_entries
        get :refresh_debtors
        get :multiple_business_accounts
        put :reconcile_account
      end
    end

    resources :notification do
      collection do
        post :send_portal_notification
      end
    end

    resources :reports do
      collection do
        get :item_reports
        get :salesperson_reports
        get :customer_reports
        get :download_item_reports
      end
    end

    resources :schemes
    resources :salesman_tracking
  end

  namespace :api do
    resources :users do
      collection do
        get :existing_user
      end
    end

    resources :orders do
      collection do
        get :customer_orders
        get :user_orders
        get :paid
        get :view_coupon
      end
    end

    resources :products do
        collection do
          get :items
          get :search_items
          get :division_names
          get :get_items
          get :offer_items
        end
    end
    resources :customers do
      collection do
        get :customer_coupons
        get :ledger
      end
    end
    resources :linograph_offers do
      collection do
        get :b2b
        get :b2c
      end
    end

    resources :coupons,  only: [] do
      collection do
        get :view_coupon
        get :redeem_coupon
      end
    end

    resources :schemes
    resources :salesman_tracking do
      collection do
        get :salesman
        get :customer
      end
    end
  end
end

app/models/customer.rb
class Customer < ApplicationRecord

  enum status: { active: 1, inactive: 2 }
  enum customer_type: {B2B: 1, B2C: 2}

  validates :username, :uniqueness => true, on: :create
  validates :phone_number, :uniqueness => true, on: :create
  validates_length_of :phone_number, is: 10,  message: "must be 10 digit long"
  validates_length_of :gstin, is: 15,  message: "must be 15 digit long", if: Proc.new { |a| a.B2B? }
  #validates_length_of :password, :in => 6..20, :on => :create
  has_many :orders
  has_many :order_products
  has_many :customer_coupons
  has_many :coupons, through: :customer_coupons
  has_one :debtor
  before_create :create_username

  def create_username
    if self.B2B?
      self.username = "cus_" + self.phone_number
    else
      self.username = "b2c_" + self.phone_number
    end

  end

  def self.import(file)
    accessible_attributes = ["name", "phone_number", "email", "address",	"company",	"gstin",	"account_number",	"ifsc",	"customer_type",	"status"]
    spreadsheet = open_spreadsheet(file)
    header = spreadsheet.row(1)
    (2..spreadsheet.last_row).each do |i|
      row = Hash[[header, spreadsheet.row(i)].transpose]
      #row["gstin"] = row["gstin"].to_i unless row["gstin"].to_i == 0
      row["phone_number"] = row["phone_number"].to_i unless row["phone_number"].to_i == 0
      row["account_number"] = row["account_number"].to_i unless row["account_number"].to_i == 0
      #row["ifsc"] = row["ifsc"].to_i unless row["ifsc"].to_i == 0
      customer = find_by_phone_number(row["phone_number"]) || new
      customer.attributes = row.to_hash.slice(*accessible_attributes)
      customer.verification = true
      customer.save!
      unless customer.debtor.present?
        Debtor.create(customer_id: customer.id, updated_by: 1)
        CustomerCouponsService.new(customer.id).add_coupon('NEW', 101, "WELCOME EaseMYSales", 2199, 28)
      end
    end
  end

  def self.open_spreadsheet(file)
    case File.extname(file.original_filename)
    when ".csv" then Csv.new(file.path, nil, :ignore)
    when ".xls" then Roo::Excel.new(file.path, nil, :ignore)
    when ".xlsx" then Roo::Excelx.new(file.path, nil, :ignore)
    else raise "Unknown file type: #{file.original_filename}"
    end
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApiController
  before_action :authenticate_user

  def index
    @q = Customer.ransack(params[:q])
    @customers = @q.result.page(params[:page])
  end

  def download_excel
    @q = Customer.ransack(params[:q])
    @customers = @q.result
    render xlsx: "customer", template: "/admin/customers/customers.xls.axlsx"
  end

  def import
    Customer.import(params[:file])
    set_flash_notification :success, :default, {:message => "Customers updated using Excel"}
    redirect_to admin_customers_path
  end

  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.new(customer_params)
    @customer.verification = true
    if @customer.save
      Debtor.create(customer_id: @customer.id, updated_by: 1)
      CustomerCouponsService.new(@customer.id).add_coupon('NEW', 101, "WELCOME EaseMYSales", 2199, 28)
      set_flash_notification :success, :create, entity: 'Customer'
      redirect_to admin_customers_path
    else
      set_instant_flash_notification :danger, :default, {:message => @customer.errors.messages.map{|k,v| "#{k} #{v.first}"}.first.humanize}
      render :new
    end
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      set_flash_notification :success, :update, entity: 'Customer'
      redirect_to admin_customers_path
    else
      set_instant_flash_notification :danger, :default, {:message => @customer.errors.messages.map{|k,v| "#{k} #{v.first}"}.first.humanize}
      render :edit
    end
  end

  def verify
    @customer = Customer.find_by(id: params[:id])
    if @customer.update(verification: true)
      set_flash_notification :success, :update, entity: 'Customer'
      redirect_to admin_customers_path
    end
  end

  private
  def customer_params
    params.require(:customer).permit(:name, :address, :phone_number, :email, :company, :gstin, :account_number, :ifsc, :status, :verification, :customer_type)
  end

end

app/controllers/api/customers_controller.rb
class Api::CustomersController < ApiController

  def index
    customers = Customer.where(status: "active")
    render_collection(customers, Api::CustomersSerializer)
  end

  def create
    customer = Customer.new(customer_params)
    customer.status = "active"
    if customer.save
      Debtor.create(customer_id: customer.id, updated_by: 1)
      CustomerCouponsService.new(customer.id).add_coupon('NEW', 101, "WELCOME Linograph", 2199, 28)
      render_success(customer, "Customer Account Created sucessfully")
    else
        render_error({}, "Error in creating customer account")
    end
  end

  def ledger
    ledgers = Debtor.where(:customer_id => params[:customer_id])
    if ledgers.present?
      render_collection(ledgers, Api::DebtorSerializer)
    else
      render_error({}, "Can't find Debtor")
    end
  end

  def customer_coupons
    customer = Customer.find(params[:id])
    customer_coupons = customer.coupons.includes(:redeemed_coupon)
    render_collection(customer_coupons, Api::CouponsSerializer)
  end

  private
  def customer_params
    params.require(:customer).permit(:name, :address, :email, :phone_number, :company, :gstin, :account_number, :ifsc, :customer_type)
  end
end

app/views/admin/customers/_form.html.erb
<div class="form-group col-md-6">
  <%= f.label :name, 'Name' %>
  <%= f.text_field :name, class: 'form-control input feedr-main-input', required: true %>

</div>

<div class="form-group col-md-6">
  <%= f.label :phone_number, 'Phone Number' %>
  <%= f.text_field :phone_number, class: 'form-control input feedr-main-input', required: true, :maxlength => 10  %>
</div>

<div class="form-group col-md-6">
  <%= f.label :address, 'Address' %>
  <%= f.text_field :address, class: 'form-control input feedr-main-input', required: true  %>
</div>

<div class="form-group col-md-6">
  <%= f.label :company, 'Company' %>
  <%= f.text_field :company, class: 'form-control input feedr-main-input', required: true  %>
</div>

<div class="form-group col-md-6">
  <%= f.label :gstin, 'GSTIN' %>
  <%= f.text_field :gstin, class: 'form-control input feedr-main-input', :maxlength => 15  %>
</div>

<div class="form-group col-md-6">
  <%= f.label :account_number, 'Account Number' %>
  <%= f.text_field :account_number, class: 'form-control input feedr-main-input', required: true  %>
</div>

<div class="form-group col-md-6">
  <%= f.label :ifsc, 'IFSC Code' %>
  <%= f.text_field :ifsc, class: 'form-control input feedr-main-input', required: true  %>
</div>

<div class="form-group col-md-6">
  <%= f.label :email, 'Email' %>
  <%= f.text_field :email, class: 'form-control input feedr-main-input' %>
</div>

<div class="form-group col-md-6">
  <%= f.label :status, 'Status' %>
  <%= f.select :status, ['active', 'inactive'], {},
               { class: 'feedr-main-select form-control ','data-behavior' => "chosen-select"} %>
</div>

<div class="form-group col-md-6">
  <%= f.label :customer_type, 'User Type' %>
  <%= f.select :customer_type, ['B2B', 'B2C'], {},
               { class: 'feedr-main-select form-control ','data-behavior' => "chosen-select"} %>
</div>

<%= javascript_include_tag 'users/form' %>

app/views/admin/customers/edit.html.erb
<div class="container col-md-8 page-body">
  <div class="row">
    <h4 class="col-md-2">
      <%= link_to admin_customers_path,  class: "btn btn-blue pull-left" do %>
        Back
      <% end %>
    </h4>
    <h4 class="col-md-8" align="center">
      Add User
    </h4>
  </div>
  <div class="row">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= form_for(@customer, :url => {:controller => 'customers', :action => 'update'}) do |f| %>
          <div class="row mrs mls new_form">
            <%= render 'form', f: f,form_type: "edit" %>
          </div>
          <div class="row">
            <div class="col-md-12" align="center">
              <%= f.submit "Update", class: 'btn btn-green' %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container-div page-body">
  <div>
    <div class="col-xs-12" align="center">
      <h3>Customers</h3>
    </div>
    <div class="col-xs-12 no-left-pad">
      <div class="col-md-2">
        <h3>
          <%= link_to new_admin_customer_path, class: "btn btn-green" do %>
            </span> Add customer
          <% end %>
        </h3>
      </div>
    </div>

    <div class="col-xs-9 mt20">
      <%= form_tag import_admin_customers_path, multipart: true do %>
        <div class="col-xs-3">
          <%= file_field_tag :file, class: 'form-control feedr-main-input', style: "font-size: 16px;", :required => true %>
        </div>
        <div class="col-xs-2" style="font-size: 16px;">
          <%= submit_tag "Import from Excel", class: 'btn btn-white', style: "font-size: 16px;" %>
        </div>
      <% end %>
      <div class="col-xs-1"></div>
      <div class="col-xs-3 btn btn-white" style="font-size: 16px;">
        <%= link_to "Export as Excel", download_excel_admin_customers_path(format: "xlsx") %>
      </div>
    </div>
    <div class="col-xs-12 mt20">
      <%= search_form_for(@q,url: admin_customers_path, id: 'customer_search_form') do |f| %>
        <div class="col-xs-2  ">
          <%=f.text_field :name_cont, class: 'form-control feedr-main-input', placeholder: 'Name'%>
        </div>
        <div class="col-xs-2  ">
          <%=f.text_field :phone_number_cont, class: 'form-control feedr-main-input', placeholder: 'Phone'%>
        </div>
        <div class="col-xs-2  ">
          <%=f.text_field :gstin_cont, class: 'form-control feedr-main-input', placeholder: 'GSTIN'%>
        </div>
        <div class="col-xs-2">
          <%= f.select :verification_eq, [true, false], {include_blank: "--Verified?--"},
                       { class: 'feedr-main-select form-control ','data-behavior' => "chosen-select"}%>
        </div>
        <a id="customer_submit" class="btn btn-default submit btn-green">
          <i class="fa fa-search" aria-hidden="true"></i></a>
      <%end%>
    </div>
  </div>

  <div class="col-xs-12 mt20">
    <table class="table table-bordered feedr-main-tabl" >
      <thead>
      <tr>
        <th class="col-xs-1">Id</th>
        <th class="col-xs-1">Name</th>
        <th class="col-xs-1">Username</th>
        <th class="col-xs-1">Phone Number</th>
        <th class="col-xs-2">Address</th>
        <th class="col-xs-1">Company</th>
        <th class="col-xs-1">GSTIN</th>
        <th class="col-xs-1">Account Number</th>
        <th class="col-xs-1">IFSC</th>
        <th class="col-xs-1">Status</th>
        <th class="col-xs-2">Action</th>
      </tr>
      </thead>
      <tbody>
      <% @customers.each do |customer| %>
        <% if !customer.verification %>
          <tr bgcolor="#f7c6b3">
        <% else %>
          <tr bgcolor="#b3f7b3">
        <% end %>
          <td><%= customer.id%></td>
          <td><%= customer.name%></td>
          <td><%= customer.username%></td>
          <td><%= customer.phone_number%></td>
          <td><%= customer.address%></td>
          <td><%= customer.company%></td>
          <td><%= customer.gstin%></td>
          <td><%= customer.account_number%></td>
          <td><%= customer.ifsc%></td>
          <td><%= customer.status%></td>
        <td>
            <%= link_to edit_admin_customer_path(customer), class: "btn btn-sm btn-blue" do %>
              Edit
            <% end %>
        <% if customer.verification == false %>
              <%= link_to 'Verify', verify_admin_customers_path(id: customer), method: :put, data: { confirm: 'This Customer will be verified. Proceed?' }, class: "btn btn-sm btn-blue" %>
        <% end %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
    <div class="page_links ppl">
      <%= will_paginate @customers%>
    </div>
  </div>
</div>

<script>
    ChosenApplier.init($('select[data-behavior=chosen-select]'));
    $('#customer_submit').on('click', function() {
        $('#customer_search_form').submit();
    });
</script>

app/views/admin/customers/new.html.erb
<div class="container col-md-8 page-body">
  <div class="row">
    <h4 class="col-md-2">
      <%= link_to admin_customers_path,  class: "btn btn-blue pull-left" do %>
        Back
      <% end %>
    </h4>
    <h4 class="col-md-8" align="center">
      Add Customer
    </h4>
  </div>
  <div class="row">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= form_for(@customer, :url => {:controller => 'customers', :action => 'create'}) do |f| %>
          <div class="row mrs mls new_form">
            <%= render 'form', f: f,form_type: "new" %>
          </div>
          <div class="row">
            <div class="col-md-12" align="center">
              <%= f.submit "Add", class: 'btn btn-green' %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>