config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #
  match 'active'  => 'admin/sessions#active',  via: :get
  match 'timeout' => 'admin/sessions#timeout', via: :get

  namespace :admin do
    get '/' => 'users#dashboard'

    resources :users do
      collection do
        get :dashboard
      end
    end

    resources :sessions do
      collection do
        get :login
        post :login_attempt
        get :logout
      end
    end
    resources :orders, only: [:index, :show, :update, :create, :new, :edit] do
      collection do
        get :download_order
        put :tracking
        get :tracking_modal
        get :paid
        get :download_excel
        get :order_detail_excel
        put :add_delivery
      end
    end
    resources :roles
    resources :permissions
    resources :product_stock do
      collection do
        get :download_excel
      end
    end
    resources :customers do
      collection do
        put :verify
        get :download_excel
        post :import
      end
    end
    #resources :customers_imports, only: [:new, :create]
    resources :product_offers do
      collection do
        post :upload_offer_image
      end
    end

    resources :products, only: [:index, :show, :update, :create, :new, :edit] do
      collection do
        post :upload_product_image
        get :download_excel
        post :import
      end
    end

    resources :product_divisions, only: [:index, :show, :update, :create, :edit, :new] do
      collection do
        post :upload_division_image
      end
    end

    resources :product_sections, only: [:index, :show, :update, :create, :edit, :new]  do
      collection do
        post :upload_section_image
      end
    end

    resources :product_departments, only: [:index, :show, :update, :create, :edit, :new]

    resources :coupons do
      collection do
        put :redeem_coupon
        post :generate_coupons
      end
    end

    resources :debtors, only: [:index, :show] do
      collection do
        get :add_entry
        post :create_entry
        post :upload_entries
        get :refresh_debtors
        get :multiple_business_accounts
        put :reconcile_account
      end
    end

    resources :notification do
      collection do
        post :send_portal_notification
      end
    end

    resources :reports do
      collection do
        get :item_reports
        get :salesperson_reports
        get :customer_reports
        get :download_item_reports
      end
    end

    resources :schemes
    resources :salesman_tracking
  end

  namespace :api do
    resources :users do
      collection do
        get :existing_user
      end
    end

    resources :orders do
      collection do
        get :customer_orders
        get :user_orders
        get :paid
        get :view_coupon
      end
    end

    resources :products do
        collection do
          get :items
          get :search_items
          get :division_names
          get :get_items
          get :offer_items
        end
    end
    resources :customers do
      collection do
        get :customer_coupons
        get :ledger
      end
    end
    resources :linograph_offers do
      collection do
        get :b2b
        get :b2c
      end
    end

    resources :coupons,  only: [] do
      collection do
        get :view_coupon
        get :redeem_coupon
      end
    end

    resources :schemes
    resources :salesman_tracking do
      collection do
        get :salesman
        get :customer
      end
    end
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  belongs_to :user,optional: true
  has_many :order_products
  has_many :products, through: :order_products
  accepts_nested_attributes_for :order_products, allow_destroy: true
  has_one :order_tracking
  belongs_to :coupon

  enum order_status: { new_order: 1, accepted:2, dispatched: 3, delivered: 4, cancelled: 5, partially_delivered: 6}
  enum is_paid: {false: 0, paid_by_customer: 1, paid_by_admin: 2}

  after_create :redeem_coupon
  after_update :add_referral

  validates_presence_of :customer_id

  accepts_nested_attributes_for :order_products, reject_if: :all_blank

  def redeem_coupon
    if coupon_id.present?
      RedeemedCoupon.create({coupon_id: coupon_id, redeemed_by: 1, redeemed_for: "to be updated"})
    end
  end

  def add_referral
    if order_status == 'delivered'
      customer_account = customer
      if customer_account.referred_by.present? && customer_account.orders.where(orders: {order_status: 'delivered'}).count == 1
        referred_customer = Customer.find_by({id: customer_account.referred_by})
        CustomerCouponsService.new(referred_customer.id).add_coupon('REF', 75, "REFFERAL BONUS", 999, 60) if referred_customer.present?
      end
    end
  end

  ransacker :created_at do
    Arel.sql("date(orders.created_at)")
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApiController
  before_action :authenticate_user

  def index
    @q = Order.includes(:customer,:user,:order_products).ransack(params[:q])
    @orders = @q.result.order(created_at: :desc).paginate(page: params[:page], per_page: 10)
  end

  def download_excel
    @q = Order.includes(:customer,:user,:order_products).ransack(params[:q])
    @orders = @q.result.order(created_at: :desc)
    render xlsx: "orders", template: "/admin/orders/orders.xls.axlsx"
  end

  def order_detail_excel
    @order = Order.find(params[:id])
    render xlsx: "order_details", template: "/admin/orders/order_detail.xls.axlsx"
  end

  def show
    @order = Order.find(params[:id])
  end

  def update
    @order = Order.find(params[:id])
    if order_params["order_products_attributes"].present?
      partial = false
      order_params["order_products_attributes"].each do |order_product|

        current = @order.order_products.find(order_product[1]["id"].to_i)
        current.dispatched_quantity+= order_product[1]["dispatched_quantity"].to_i
        if(current.quantity != current.dispatched_quantity)
          partial = true
        end
        stock = current.product.stock_quantity - order_product[1]["dispatched_quantity"].to_i
        current.product.update(:stock_quantity => stock)
        current.save
      end
      if partial
        @order.order_status = "partially_delivered"
      else
        @order.order_status = "dispatched"
      end
      entity = 'Order Delivery'
    else
      @order.attributes = order_params
      entity = 'Order Status'
    end
    if @order.order_status_changed?
      NotificationService.new(@order).send_notification
      #if @order.order_status == "dispatched"
      #  @order.order_products.each do |order_product|
      #  product = Product.find(order_product.product_id)
      #  product.stock_quantity-=order_product.quantity
      #  product.save
      #  end
      #end
    end
    if @order.save
      set_flash_notification :success, :update, entity: entity
      redirect_to admin_orders_path
    else
      set_instant_flash_notification :danger, :default, {:message => @order.errors.messages.map{|k,v| "#{k} #{v.first}"}.first.humanize}
      render :edit
    end
  end

  def tracking_modal
    @tracking = OrderTracking.where(order_id: params[:id]).first_or_initialize
  end

  def tracking
    @tracking = OrderTracking.where(order_id: tracking_params["order_id"].to_i).first_or_initialize
    @tracking.attributes = tracking_params
    if @tracking.save
      set_flash_notification :success, :update, entity: 'Order Tracking'
      redirect_to admin_orders_path
    else
      set_instant_flash_notification :danger, :default, {:message => @order.errors.messages.map{|k,v| "#{k} #{v.first}"}.first.humanize}
      render :edit
    end
  end

  def download_order
    @order = Order.find(params[:id])

    render   pdf: "order_"+@order.id.to_s,
             locals: { order: @order },
             template: 'admin/orders/order.pdf.erb',
             disposition: 'attachment',
             formats: :html, encoding: 'utf8'
    #send_file pdf, filename: 'whatever.pdf',type: "application/pdf"
  end

  def paid
    order = Order.find(params[:id])
    order.is_paid = "paid_by_admin"
    if order.save
      set_flash_notification :success, :default, {:message => "Order Marked as paid"}
      redirect_back(fallback_location: "admin/orders/#{order.id}")
    else
      set_flash_notification :danger, :default, {:message => "Error Marking as paid"}
      redirect_back(fallback_location: "admin/orders/#{order.id}")
    end
  end

  private
  def order_params
    params.require(:order).permit(:order_status, :order_track_id,  order_products_attributes: [:id, :dispatched_quantity])
  end

  def tracking_params
    params.require(:order_tracking).permit(:order_id, :tracking_id, :transport_name, :no_of_pkg, :weight, :freight, :tracking_url)
  end
end

app/controllers/api/orders_controller.rb
class Api::OrdersController < ApiController

  def index
      orders = Order.includes(:user,:customer, order_products: [:product])
    render_collection(orders, Api::OrdersListSerializer)
  end

  def create
    order = Order.new(order_params)
    order.order_status = "new_order"
    if order.save
      OrderMailer.order_mail(order).deliver
      render_success({}, "Order created sucessfully", { order_id: order.id})
    else
      render_error({}, "Error in creating order ", { errors: order.errors.full_messages})
    end
  end

  def show
    orders = Order.includes(order_products: [:product]).where(id: params[:id])
    render_collection(orders, Api::OrdersListSerializer)
  end

  def customer_orders
    orders = Order.includes(:customer, order_products: [:product]).where(customer_id: params[:customer_id]).order(created_at: :desc)
    render_collection(orders, Api::OrdersListSerializer)
  end

  def user_orders
    orders = Order.includes(:user, order_products: [:product]).where(user_id: params[:user_id]).order(created_at: :desc)
    render_collection(orders, Api::OrdersListSerializer)
  end

  def paid
    order = Order.find(params[:id])
    order.is_paid = "paid_by_customer"
    if order.save
      render json: {success: "Success", code: "200", message: "Paid By customer"}
    else
      render json: {success: "Failed", code: "201", message: order.errors}
    end
  end

  def get_coupon

  end

  def view_coupon
    coupon = Coupon.find_by({code: params[:code]})
    if !coupon.present?
      render_success({status: "-1", message: "Coupon Not Present"}, "", {})
    elsif coupon.customer_coupon.try(:customer_id) != params[:customer_id].to_i
      render_success({status: "-1", message: "Coupon Not Valid for this user"}, "", {})
    elsif coupon.redeemed_coupon.present?
      render_success({status: "-1", message: "Coupon Already Redeemed"}, "", {})
    elsif coupon.expired_at < Date.today
      render_success({status: "-1", message: "Coupon Expired"}, "", {})
    else
      render_success({status: "1", coupon_details: {data: coupon}}, "", {})
    end
  end

  private
  def order_params
    params.require(:order).permit(:id,:user_id,:customer_id, :phone, :customer_address, :order_amount, :coupon_id, :comment, order_products_attributes: [:id, :product_id, :mrp, :discount, :rsp, :quantity])
  end

end

app/views/admin/orders/_tracking_modal.html.erb
<div class="modal fade page-body" id="GenerateCouponsModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <div class="modal-title text-head" align="center">Tracking Details</div>
      </div>
        <%= form_for @tracking, url: tracking_admin_orders_path, method: "put" do |f| %>
        <div class="col-xs-12 modal-body">

            <div class="col-xs-6">
              <%= label_tag :tracking_id, 'Order Tracking Id:'%>

              <%= f.text_field :tracking_id, class: 'form-control input feedr-main-input' %>
            </div>
            <div class="col-xs-6 hide">
              <%= f.text_field :order_id, value: @tracking.order_id, class: 'form-control input feedr-main-input' %>
            </div>
            <div class="col-xs-6">
              <%= label_tag :transport_name, 'Transport Name:'%>
              <%= f.text_field :transport_name, class: 'form-control input feedr-main-input' %>
            </div>
            <div class="col-xs-6">
              <%= label_tag :no_of_pkg, 'Number of Package:'%>
              <%= f.text_field :no_of_pkg, class: 'form-control input feedr-main-input' %>
            </div>
            <div class="col-xs-6">
              <%= label_tag :weight, 'Weight:'%>
              <%= f.text_field :weight, class: 'form-control input feedr-main-input' %>
            </div>
            <div class="col-xs-6">
              <%= label_tag :freight, 'Freight:'%>
              <%= f.text_field :freight, class: 'form-control input feedr-main-input' %>
            </div>
            <div class="col-xs-6">
              <%= label_tag :tracking_url, 'Tracking Url:'%>
              <%= f.text_field :tracking_url, class: 'form-control input feedr-main-input' %>
            </div>
        </div>
        <div class="modal-footer mt20">
          <%= f.submit "Update", class: 'btn btn-green' %>
        </div>
        <% end %>
    </div>
  </div>
</div>

app/views/admin/orders/index.html.erb
<div class="container-div page-body">
  <div>
    <div class="col-xs-12" align="center">
      <h3>Orders</h3>
    </div>
    <div class="col-xs-12" style="padding-left: 30px">
      <div class="btn btn-white" style="font-size: 16px;">
        <%= link_to "Export as Excel", download_excel_admin_orders_path(format: "xlsx") %>
      </div>
    </div>
    <div class="col-xs-12 mt20">
      <%= search_form_for(@q,url: admin_orders_path, id: 'order_search_form') do |f| %>
        <div class="col-xs-2  ">
          <%=f.text_field :phone_cont, class: 'form-control feedr-main-input', placeholder: 'Phone'%>
        </div>
        <div class="col-xs-2">
        <%= f.select :customer_id_eq, options_from_collection_for_select(Customer.active, :id, :company), {include_blank: "--Select Company--"},
                     { class: 'feedr-main-select form-control ','data-behavior' => "chosen-select"}%>
        </div>
        <div class="col-xs-2">
          <%= f.select :order_status_eq, Order.order_statuses.map { |key, value| [key.humanize, value] }, {include_blank: "--Select a Status--"},
                       { class: 'feedr-main-select form-control ','data-behavior' => "chosen-select", required: true}%>
        </div>
        <a id="order_submit" class="btn btn-default submit btn-green">
          <i class="fa fa-search" aria-hidden="true"></i></a>
      <%end%>
    </div>
  </div>
  <div class="col-xs-12 mt20">
    <table class="table table-bordered table-striped table-hover table-data table-overview display" >
      <thead>
      <tr>
        <th class="col-xs-1">Id</th>
        <th class="col-xs-1">Sales Person</th>
        <th class="col-xs-1">Customer</th>
        <th class="col-xs-1">Phone</th>
        <th class="col-xs-2">Address</th>
        <th class="col-xs-1">Order Status</th>
        <th class="col-xs-2">Order Summary</th>
        <th class="col-xs-1">Order Date</th>
        <th class="col-xs-1">Updated At</th>
        <th class="col-xs-1">Action</th>
      </tr>
      </thead>
      <tbody>
      <% @orders.each do |order| %>
          <tr>
            <td><%= order.id%></td>
            <td><%= order.user.try(:name)%></td>
            <td><%= order.customer.try(:name)%></td>
            <td><%= order.phone%></td>
            <td><%= order.customer_address%></td>
            <td><%= order.order_status%></td>
            <td><%= order.order_products.sum(:quantity) %> units | <b>&#8377;</b>
              <% if order.coupon.present? %>
                <% if order.coupon.coupon_type == "fixed_value" %>
                  <%= order.order_amount - order.coupon.amount %>
                <% else %>
                  <%= order.order_amount - ((order.coupon.amount*order.order_amount)/100) %>
                <% end %>
              <% else %>
                <%= order.order_amount %>
              <% end %>
                </td>
                <td><%= order.created_at.strftime("%d-%m-%Y  -  %H:%M") %></td>
                <td><%= order.updated_at.strftime("%d-%m-%Y  -  %H:%M") %></td>
            <td>
              <%= link_to admin_order_path(order), class: "btn btn-sm btn-blue" do %>
                View
              <% end %>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>
    <div class="page_links ppl">
      <%= will_paginate @orders%>
    </div>
  </div>
</div>

<script>
    ChosenApplier.init($('select[data-behavior=chosen-select]'));
    $('#order_submit').on('click', function() {
        $('#order_search_form').submit();
    });
</script>

app/views/admin/orders/show.html.erb
<div class="container col-md-10 page-body">
  <div class="row">
    <h4 class="col-md-2 col-xs-offset-2" style="padding-top: 50px">
      <%= link_to admin_orders_path,  class: "btn btn-blue pull-left" do %>
        Back
      <% end %>
    </h4>
    <h3 class="col-md-4" align="center">
      Order Details
    </h3>
  </div>
  <div class="col-xs-10 col-xs-offset-1">
    <div class="panel panel-default">
      <div class="panel-body">
        <div class="col-xs-12 mt20">
          <div class="col-xs-6">
            <%= label_tag 'Customer: '%>&nbsp&nbsp<%= @order.customer.try(:name) %>
          </div>
          <div class="col-xs-6">
            <%= label_tag 'Customer Phone: '%>&nbsp&nbsp<%= @order.phone %>
          </div>
        </div>
        <div class="col-xs-12 mt10">
          <div class="col-xs-6">
            <%= label_tag 'Address: '%>&nbsp&nbsp<%= @order.customer_address %>
          </div>
          <div class="col-xs-6">
            <%= label_tag 'Date: '%>&nbsp&nbsp<%= @order.created_at.strftime("%d-%m-%Y  -  %H:%M") %>
          </div>
        </div>

        <div class="col-xs-12 mt10">
          <% if @current_user.user_type == 'super_admin' and @order.order_status != "cancelled" and @order.order_status !="delivered"  %>
            <div class="col-xs-2">
              <%= label_tag 'Order Status: '%></div>
            <div class="col-xs-2">
              <%= form_for @order, url: admin_order_path do |f| %>
                <%= f.select :order_status, Order.order_statuses.keys, {},
                             { class: 'feedr-main-select form-control ','data-behavior' => "chosen-select"} %>
                </div>
                <div class="col-xs-2"><%= f.submit "Update", class: 'btn btn-green' %>
                </div>
              <% end %>
          <% else %>
            <div class="col-xs-6">
              <%= label_tag 'Order Status: '%>&nbsp&nbsp<%= @order.order_status.titleize %>
            </div>
          <% end %>
          <% if @order.is_paid == "paid_by_admin" %>
            <div class="col-xs-6">
              <%= label_tag 'Payment Status: '%>&nbsp&nbsp<b>Paid</b>
            </div>
          <% else %>
            <div class="col-xs-6">
              <%= label_tag 'Payment Status: '%>&nbsp&nbsp
              <div class="btn btn-white">
                <%= link_to controller: "orders", action: "paid", id: @order.id do %>
                  Mark as Paid
                <% end %>
              </div>
            </div>
          <% end %>
        </div>
        <div class="col-xs-12 mt20">
          <div class="col-xs-2">
          <%= label_tag 'Tracking Details: '%>&nbsp&nbsp
          </div>
          <div class="btn btn-white">
            <%= link_to controller: "orders", action: "tracking_modal", id: @order.id, remote:true do %>
              Add/Edit
            <% end %>
          </div>
          </div>
        </div>
        </div>

        <div class="col-xs-10 col-xs-offset-1 mt20">
          <table class="table table-bordered" id="products">
            <thead>
            <tr>
              <th class="col-xs-1">S No.</th>
              <th class="col-xs-5">Item</th>
              <th class="col-xs-1">Mrp</th>
              <th class="col-xs-1">Discount</th>
              <th class="col-xs-1">Rsp</th>
              <th class="col-xs-1">Order Quantity</th>
              <th class="col-xs-1">Delivered Quantity</th>
              <th class="col-xs-1">Stock</th>
              <th class="col-xs-1">Total</th>
              <th class="col-xs-1">To Deliver?</th>
            </tr>
            </thead>
            <tbody>
            <%= nested_form_for(@order, :url => {:controller => 'orders', :action => 'update'}, :method => 'put') do |f| %>
            <% #@order.order_products.each_with_index do |item, index| %>
              <% count=1 %>
                <%= f.fields_for :order_products do |task_form| %>
              <% if task_form.object.product.stock_quantity < task_form.object.quantity.to_i and (@order.order_status == "new_order" or @order.order_status == "accepted" or @order.order_status == "partially_delivered") %>
                <tr bgcolor="#f7c6b3">
              <% else %>
                <tr>
              <% end %>
                <td><%= count %></td>
                <td><%= task_form.object.product.try(:name)%></td>
                <td><%= task_form.object.mrp %></td>
                <td><%= task_form.object.discount %></td>
                <td><%= task_form.object.rsp %></td>
                <td class="quantity"><%= task_form.object.quantity%></td>
                <td class="dispatched_quantity"><%= task_form.object.dispatched_quantity %></td>
                <td class="stock"><%= task_form.object.product.stock_quantity %></td>
                <td><%= task_form.object.rsp.to_i * task_form.object.quantity.to_i %></td>
                <td>
                  <% if task_form.object.dispatched_quantity == task_form.object.quantity or @order.order_status == "delivered" %>
                    <%= task_form.number_field :dispatched_quantity, class: 'form-control input feedr-main-input add_delivery' %>
                  <% else %>
                    <%= task_form.number_field :dispatched_quantity, class: 'form-control input feedr-main-input add_delivery'%>
                  <% end %>
                </td>
              </tr>
            <% count+=1 %>
                <% end %>
            <%# end %>

            <tr>
              <td colspan="8" style="text-align: right; padding-right: 10px">
                <b>
                  <div>
                    <%= label_tag 'Order Amount ', nil,style:"width: 120px;text-align: left;"%>
                    <%= label_tag @order.order_amount.to_f, nil,style:"width: 116px;text-align: right;"%>
                  </div>
                  <% if @order.coupon_id.present? %>
                    <div>
                      <%= label_tag 'Coupon Code ', nil,style:"width: 120px;text-align: left;"%>
                      <%= label_tag @order.coupon.code,  nil,style:"width: 116px;text-align: right"%>
                    </div>
                    <% if @order.coupon.coupon_type == "fixed_value" %>
                    <div>
                      <%= label_tag 'Coupon Discount ', nil,style:"width: 120px;text-align: left;"%>
                      <%= label_tag @order.coupon.amount,  nil,style:"width: 116px;text-align: right;"%>
                    </div>
                    <div>
                      <%= label_tag 'Total Amount ', nil,style:"width: 120px;text-align: left;"%>
                      <%= label_tag @order.order_amount - @order.coupon.amount, nil,style:"width: 116px;text-align: right;"%>
                    </div>
                    <% else %>
                      <div>
                        <%= label_tag 'Coupon Discount ', nil,style:"width: 120px;text-align: left;"%>
                        <%= label_tag @order.coupon.amount.to_s + "%",  nil,style:"width: 116px;text-align: right;"%>
                      </div>
                      <div>
                        <%= label_tag 'Total Amount ', nil,style:"width: 120px;text-align: left;"%>
                        <%= label_tag @order.order_amount - ((@order.coupon.amount*@order.order_amount)/100), nil,style:"width: 116px;text-align: right;"%>
                      </div>
                    <% end %>
                  <% else %>
                  <div>
                    <%= label_tag 'Total Amount ', nil,style:"width: 120px;text-align: left;"%>
                    <%= label_tag @order.order_amount, nil,style:"width: 116px;text-align: right;"%>
                  </div>
                  <% end %>
                </b>
              </td>
              <td colspan="4">
                <% if @order.order_status != "delivered" %>
                <div class="col-md-12" align="left">
                  <%= f.submit "Add Delivery", class: 'btn btn-blue deliver' %>
                </div>
                <% end %>
              </td>
            </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
<div class="col-md-5 col-xs-offset-8">
  <%= link_to download_order_admin_orders_path(id: @order.id), class: "btn btn-blue", style: "font-size: 16px;" do %>
    Download PDF
  <% end %>
  <div class="btn btn-white" style="font-size: 16px;">
    <%= link_to "Export as Excel", order_detail_excel_admin_orders_path(format: "xlsx", id: @order.id) %>
  </div>
</div>
</div>

<script>

    $(function () {
        var bool = true;
        $('#products > tbody  > tr').each(function() {
            var quantity = $(this).find('.quantity').text();
            var dis_quantity = $(this).find('.dispatched_quantity').text();
            var stock = $(this).find('.stock').text();
            var delivery = ((quantity-dis_quantity) >= stock)?stock:(quantity-dis_quantity);

            if(delivery != 0)
                bool = false;
            if(delivery<0)
                delivery = 0;
            $(this).find(".add_delivery").val(delivery);
        });
        //if(bool)
         // $('.deliver').hide();
    });

</script>

app/views/admin/orders/tracking_modal.js.erb
$('<%= j render "tracking_modal" %>').modal()