config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #
  match 'active'  => 'admin/sessions#active',  via: :get
  match 'timeout' => 'admin/sessions#timeout', via: :get

  namespace :admin do
    get '/' => 'users#dashboard'

    resources :users do
      collection do
        get :dashboard
      end
    end

    resources :sessions do
      collection do
        get :login
        post :login_attempt
        get :logout
      end
    end
    resources :orders, only: [:index, :show, :update, :create, :new, :edit] do
      collection do
        get :download_order
        put :tracking
        get :tracking_modal
        get :paid
        get :download_excel
        get :order_detail_excel
        put :add_delivery
      end
    end
    resources :roles
    resources :permissions
    resources :product_stock do
      collection do
        get :download_excel
      end
    end
    resources :customers do
      collection do
        put :verify
        get :download_excel
        post :import
      end
    end
    #resources :customers_imports, only: [:new, :create]
    resources :product_offers do
      collection do
        post :upload_offer_image
      end
    end

    resources :products, only: [:index, :show, :update, :create, :new, :edit] do
      collection do
        post :upload_product_image
        get :download_excel
        post :import
      end
    end

    resources :product_divisions, only: [:index, :show, :update, :create, :edit, :new] do
      collection do
        post :upload_division_image
      end
    end

    resources :product_sections, only: [:index, :show, :update, :create, :edit, :new]  do
      collection do
        post :upload_section_image
      end
    end

    resources :product_departments, only: [:index, :show, :update, :create, :edit, :new]

    resources :coupons do
      collection do
        put :redeem_coupon
        post :generate_coupons
      end
    end

    resources :debtors, only: [:index, :show] do
      collection do
        get :add_entry
        post :create_entry
        post :upload_entries
        get :refresh_debtors
        get :multiple_business_accounts
        put :reconcile_account
      end
    end

    resources :notification do
      collection do
        post :send_portal_notification
      end
    end

    resources :reports do
      collection do
        get :item_reports
        get :salesperson_reports
        get :customer_reports
        get :download_item_reports
      end
    end

    resources :schemes
    resources :salesman_tracking
  end

  namespace :api do
    resources :users do
      collection do
        get :existing_user
      end
    end

    resources :orders do
      collection do
        get :customer_orders
        get :user_orders
        get :paid
        get :view_coupon
      end
    end

    resources :products do
        collection do
          get :items
          get :search_items
          get :division_names
          get :get_items
          get :offer_items
        end
    end
    resources :customers do
      collection do
        get :customer_coupons
        get :ledger
      end
    end
    resources :linograph_offers do
      collection do
        get :b2b
        get :b2c
      end
    end

    resources :coupons,  only: [] do
      collection do
        get :view_coupon
        get :redeem_coupon
      end
    end

    resources :schemes
    resources :salesman_tracking do
      collection do
        get :salesman
        get :customer
      end
    end
  end
end

app/controllers/admin/reports_controller.rb
class Admin::ReportsController < ApiController
  before_action :authenticate_user

  def index

  end

  def item_reports
    @q = Order.ransack(params[:q])
    @orders = @q.result
    @order_products = OrderProduct.where(order_id: @orders.ids)
    @products = Product.includes(:product_division).all
  end

  def salesperson_reports
    if params[:q].nil?
      params[:q] = {"created_at_lteq" => Time.now().strftime("%Y-%m-%d"), "created_at_gteq" => (Time.now() - 10.day).strftime("%Y-%m-%d")}
    end
    @q = Order.where.not(:user_id => nil).ransack(params[:q])
    @orders = @q.result
    @order_products = OrderProduct.where(order_id: @orders.ids)
    @invoice = {}
    @quantity = {}
    params[:q]["created_at_gteq"].upto(params[:q]["created_at_lteq"]) do |date|
      date = Date.parse(date) rescue nil
      if !date.nil?
        @invoice[date] = @order_products.where(:created_at => date.midnight..date.end_of_day).sum('rsp * quantity')
        @quantity[date] = @order_products.where(:created_at => date.midnight..date.end_of_day).sum('quantity')
      end
    end
  end

  def customer_reports
    if params[:q].nil?
      params[:q] = {"created_at_lteq" => Time.now().strftime("%Y-%m-%d"), "created_at_gteq" => (Time.now() - 10.day).strftime("%Y-%m-%d")}
    end
    @q = Order.ransack(params[:q])
    @orders = @q.result
    @order_products = OrderProduct.where(order_id: @orders.ids)
    @invoice = {}
    @quantity = {}
    params[:q]["created_at_gteq"].upto(params[:q]["created_at_lteq"]) do |date|
      date = Date.parse(date) rescue nil
      if !date.nil?
        @invoice[date] = @order_products.where(:created_at => date.midnight..date.end_of_day).sum('rsp * quantity')
        @quantity[date] = @order_products.where(:created_at => date.midnight..date.end_of_day).sum('quantity')
      end
    end
  end

  def download_item_reports
    @order_products = OrderProduct.where(order_id: params[:ids])
    @products = Product.includes(:product_division).all
    render xlsx: "item_reports", template: "/admin/reports/item_reports.xls.axlsx"
  end

end

app/views/admin/reports/customer_reports.html.erb
<div class="container-div page-body">
  <div class="col-xs-12 text-head" >
    <h1>Customer Report</h1>
  </div>
  <div class="container" align = "center">
    <div class="col-xs-12">
      <%= form_for(@q,url: customer_reports_admin_reports_path, method: 'get', id: 'reports_search_form', html: { autocomplete: "off" }) do |f| %>
        <div class="col-xs-3 ">
          <%= f.text_field :created_at_gteq, :placeholder => 'From Date', class: 'form-control datepicker feedr-main-input' %>
        </div>
        <div class="col-xs-3 ">
          <%= f.text_field :created_at_lteq, :placeholder => 'To Date', class: 'form-control datepicker feedr-main-input' %>
        </div>
        <div class="col-md-3">
          <%=f.select :customer_id_eq, companies_for_select, {include_blank: 'Select Company'},class: 'form-control feedr-main-select', 'data-behavior' => "chosen-select" %>
        </div>
        <div class="col-md-2">
          <%=f.submit 'Search', class: 'form-control btn btn-green'%>
        </div>
      <%end%>
    </div>
    <div class="col-xs-12 mt20">
      <h2> Total Invoice </h2>
      <%= line_chart @invoice %>
    </div>
    <div class="col-xs-12 mt20">
      <h2> Total Quantity</h2>
      <%= line_chart @quantity %>
    </div>

  </div>
</div>

<script>
    ChosenApplier.init($('select[data-behavior=chosen-select]'));
    $( document ).ready(function() {
        $('.datepicker').datepicker({dateFormat: "yy-mm-dd"});
    });
</script>

app/views/admin/reports/item_reports.html.erb
<div class="container-div page-body">
  <div>
    <div class="col-xs-12" align="center">
      <h3>Product Reports</h3>
    </div>

    <div class="col-xs-12 mt20">
      <%= form_for(@q,url: item_reports_admin_reports_path, method: 'get', id: 'reports_search_form', html: { autocomplete: "off" }) do |f| %>
        <div class="col-xs-2 ">
          <%= f.text_field :created_at_gteq, :placeholder => 'From Date', class: 'form-control datepicker feedr-main-input' %>
        </div>
        <div class="col-xs-2 ">
          <%= f.text_field :created_at_lteq, :placeholder => 'To Date', class: 'form-control datepicker feedr-main-input' %>
        </div>
        <div class="col-md-2">
          <%=f.select :customer_id_eq, companies_for_select, {include_blank: 'Select a company'},class: 'form-control feedr-main-select', 'data-behavior' => "chosen-select" %>
        </div>
        <div class="col-md-2">
          <%=f.submit 'Search', class: 'form-control btn btn-green'%>
        </div>
      <%end%>
    </div>
  </div>

  <div class="col-xs-12 mt20">
    <table class="table table-bordered table-striped feedr-main-tabl" >
      <thead>
      <tr>
        <th class="col-xs-1">Id</th>
        <th class="col-xs-2">Division</th>
        <th class="col-xs-2">Section</th>
        <th class="col-xs-2">Product Name</th>
        <th class="col-xs-1">Article Number</th>
        <th class="col-xs-2">Quantity Sold</th>
        <th class="col-xs-2">Total Invoice</th>
      </tr>
      </thead>
      <tbody>
      <% @products.each_with_index do |product, index| %>
        <td><%= index+1 %></td>
        <td><%= product.product_division.try(:name) %></td>
        <td><%= product.product_section.try(:name) %></td>
        <td><%= product.name %></td>
        <td><%= product.article_number %></td>
        <td><%= @order_products.group(:product_id).sum(:quantity)[product.id].to_i %></td>
        <td><%= @order_products.group(:product_id).sum('rsp * quantity')[product.id].to_f  %></td>
        </tr>
      <% if index+1==10 %>
        <% break %>
      <% end %>
      <% end %>
      </tbody>
    </table>
    <div class="col-xs-12" align="right">
      <div class="col-xs-1 btn btn-white" style="font-size: 16px;">
        <%= link_to "View all", download_item_reports_admin_reports_path(format: "xlsx", :ids => @orders.ids) %>
      </div>
    </div>
  </div>
</div>

<script>
    ChosenApplier.init($('select[data-behavior=chosen-select]'));
    $( document ).ready(function() {
        $('.datepicker').datepicker({dateFormat: "yy-mm-dd"});
    });
</script>

app/views/admin/reports/salesperson_reports.html.erb
<div class="container-div page-body">
    <div class="col-xs-12 text-head" >
      <h1>Sales Rep Report</h1>
    </div>
<div class="container" align = "center">
  <div class="col-xs-12">
    <%= form_for(@q,url: salesperson_reports_admin_reports_path, method: 'get', id: 'reports_search_form', html: { autocomplete: "off" }) do |f| %>
      <div class="col-xs-3 ">
        <%= f.text_field :created_at_gteq, :placeholder => 'From Date', class: 'form-control datepicker feedr-main-input' %>
      </div>
      <div class="col-xs-3 ">
        <%= f.text_field :created_at_lteq, :placeholder => 'To Date', class: 'form-control datepicker feedr-main-input' %>
      </div>
      <div class="col-md-3">
        <%=f.select :user_id_eq, salesperson_for_select, {include_blank: 'Select a Sales Rep'},class: 'form-control feedr-main-select', 'data-behavior' => "chosen-select" %>
      </div>
      <div class="col-md-2">
        <%=f.submit 'Search', class: 'form-control btn btn-green'%>
      </div>
    <%end%>
  </div>
  <div class="col-xs-12 mt20">
  <h2> Total Invoice </h2>
  <%= line_chart @invoice %>
  </div>
  <div class="col-xs-12 mt20">
    <h2> Total Quantity </h2>
    <%= line_chart @quantity %>
  </div>

</div>
</div>

<script>
    ChosenApplier.init($('select[data-behavior=chosen-select]'));
    $( document ).ready(function() {
        $('.datepicker').datepicker({dateFormat: "yy-mm-dd"});
    });
</script>