config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #
  match 'active'  => 'admin/sessions#active',  via: :get
  match 'timeout' => 'admin/sessions#timeout', via: :get

  namespace :admin do
    get '/' => 'users#dashboard'

    resources :users do
      collection do
        get :dashboard
      end
    end

    resources :sessions do
      collection do
        get :login
        post :login_attempt
        get :logout
      end
    end
    resources :orders, only: [:index, :show, :update, :create, :new, :edit] do
      collection do
        get :download_order
        put :tracking
        get :tracking_modal
        get :paid
        get :download_excel
        get :order_detail_excel
        put :add_delivery
      end
    end
    resources :roles
    resources :permissions
    resources :product_stock do
      collection do
        get :download_excel
      end
    end
    resources :customers do
      collection do
        put :verify
        get :download_excel
        post :import
      end
    end
    #resources :customers_imports, only: [:new, :create]
    resources :product_offers do
      collection do
        post :upload_offer_image
      end
    end

    resources :products, only: [:index, :show, :update, :create, :new, :edit] do
      collection do
        post :upload_product_image
        get :download_excel
        post :import
      end
    end

    resources :product_divisions, only: [:index, :show, :update, :create, :edit, :new] do
      collection do
        post :upload_division_image
      end
    end

    resources :product_sections, only: [:index, :show, :update, :create, :edit, :new]  do
      collection do
        post :upload_section_image
      end
    end

    resources :product_departments, only: [:index, :show, :update, :create, :edit, :new]

    resources :coupons do
      collection do
        put :redeem_coupon
        post :generate_coupons
      end
    end

    resources :debtors, only: [:index, :show] do
      collection do
        get :add_entry
        post :create_entry
        post :upload_entries
        get :refresh_debtors
        get :multiple_business_accounts
        put :reconcile_account
      end
    end

    resources :notification do
      collection do
        post :send_portal_notification
      end
    end

    resources :reports do
      collection do
        get :item_reports
        get :salesperson_reports
        get :customer_reports
        get :download_item_reports
      end
    end

    resources :schemes
    resources :salesman_tracking
  end

  namespace :api do
    resources :users do
      collection do
        get :existing_user
      end
    end

    resources :orders do
      collection do
        get :customer_orders
        get :user_orders
        get :paid
        get :view_coupon
      end
    end

    resources :products do
        collection do
          get :items
          get :search_items
          get :division_names
          get :get_items
          get :offer_items
        end
    end
    resources :customers do
      collection do
        get :customer_coupons
        get :ledger
      end
    end
    resources :linograph_offers do
      collection do
        get :b2b
        get :b2c
      end
    end

    resources :coupons,  only: [] do
      collection do
        get :view_coupon
        get :redeem_coupon
      end
    end

    resources :schemes
    resources :salesman_tracking do
      collection do
        get :salesman
        get :customer
      end
    end
  end
end

app/models/offer.rb
class Offer < ApplicationRecord
  has_many :offer_products
  has_many :products, through: :offer_products
  accepts_nested_attributes_for :offer_products, allow_destroy: true

  enum status: { active: 1, inactive: 2 }
  enum offer_type: { b2b: 1, b2c: 2 }
end

app/controllers/admin/product_offers_controller.rb
class Admin::ProductOffersController < ApiController
  before_action :authenticate_user

  def index
    @q = Offer.ransack(params[:q])
    @offers = @q.result.paginate(page: params[:page], per_page: 10)
  end

  def new
    @offer = Offer.new
  end

  def create
    @offer = Offer.new(cat_params)
    if @offer.save
      set_flash_notification :success, :create, entity: ' Offer'
      redirect_to admin_product_offers_path
    else
      set_instant_flash_notification :danger, :default, {:message => @offer.errors.messages[:base][0]}
      render :new
    end
  end

  def edit
    @offer = Offer.find(params[:id])
  end

  def update
    @offer = Offer.find(params[:id])
    if @offer.update(cat_params)
      set_flash_notification :success, :update, entity: ' Offer'
      redirect_to admin_product_offers_path
    else
      set_instant_flash_notification :danger, :default, {:message => @offer.errors.messages.map{|k,v| "#{k} #{v.first}"}.first.humanize}
      render :edit
    end
  end

  def upload_offer_image
    UploadToS3Service.new(params["document_#{params[:id]}"], params[:id], {extension: 'jpg', public_read: true, upload_folder: "offers"}).update_file
    Offer.find_by(id: params[:id]).try(:touch)
    set_flash_notification :success, :update, entity: 'Offer Image'
    redirect_to admin_product_offers_path
  end

  private

  def cat_params
    params.require(:offer).permit(:name, :description, :order, :offer_type, :status, product_ids: [])
  end
end

app/views/admin/product_offers/_form.html.erb
<div class="form-group col-md-6">
  <%= f.label :name, 'Name' %>
  <%= f.text_field :name, class: 'form-control input feedr-main-input', required: true %>
</div>

<div class="form-group col-md-6">
  <%= f.label :description, 'Description' %>
  <%= f.text_field :description, class: 'form-control input feedr-main-input', required: true %>
</div>

<div class="form-group col-md-6">
  <%= f.label :offer_type, 'Offer Type' %>
  <%= f.select :offer_type, ['b2b', 'b2c'], {},
               { class: 'feedr-main-select form-control ','data-behavior' => "chosen-select"} %>
</div>

<div class="form-group col-md-6">
  <%= f.label :status, 'Status' %>
  <%= f.select :status, ['active', 'inactive'], {},
               { class: 'feedr-main-select form-control ','data-behavior' => "chosen-select"} %>
</div>

<div class="form-group col-md-12">
  <%= f.label :product_ids, 'Products' %>
  <%= f.select :product_ids, Product.pluck(:name, :id), {},
               { class: 'feedr-main-select form-control ','data-behavior' => "chosen-select", multiple: true, required: true} %>
</div>

<script>
    ChosenApplier.init($('select[data-behavior=chosen-select]'))
</script>

app/views/admin/product_offers/edit.html.erb
<div class="container col-md-8 page-body">
  <div class="row">
    <h4 class="col-md-2">
      <%= link_to admin_product_offers_path,  class: "btn btn-blue pull-left" do %>
        Back
      <% end %>
    </h4>
    <h4 class="col-md-8" align="center">
      Add Offer
    </h4>
  </div>
  <div class="row">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= form_for(@offer, :url => {:controller => 'product_offers', :action => 'update'}) do |f| %>
          <div class="row mrs mls new_form">
            <%= render 'form', f: f,form_type: "edit" %>
          </div>
          <div class="row">
            <div class="col-md-12" align="center">
              <%= f.submit "Update", class: 'btn btn-green' %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/product_offers/index.html.erb
<div class="container-div page-body">
  <div>
    <div class="col-xs-12" align="center">
      <h3><u>Promotional Offer</u></h3>
    </div>
    <div class="col-xs-12 no-left-pad">
      <div class="col-md-2 col-md-offset-2 ">
        <h3>
          <%= link_to new_admin_product_offer_path, class: "btn btn-green" do %>
            </span> Add Offer
          <% end %>
        </h3>
      </div>
    </div>
  </div>

  <div class="col-xs-10 col-xs-offset-1">
    <table class="table table-bordered table-striped feedr-main-tabl" >
      <thead>
      <tr>
        <th class="col-xs-1">Id</th>
        <th class="col-xs-1">Name</th>
        <th class="col-xs-2">Description</th>
        <th class="col-xs-4">Product</th>
        <th class="col-xs-2">Status</th>
        <th class="col-xs-1">Action</th>
      </tr>
      </thead>
      <tbody>
      <% @offers.each do |offer| %>
        <tr>
          <td><%= offer.id%></td>
          <td><%= offer.name%></td>
          <td><%= offer.description%></td>
          <td>
            <ul type="disc">
              <% offer.products.each_with_index do  |item, index|%>
                <li><%= "#{index+1}. #{item.name.titleize}" %></li>
              <% end %>
            </ul>
          </td>
          <td><%= offer.status%></td>
          <td>
            <div>
              <div class="col-xs-12">
                <%= link_to edit_admin_product_offer_path(offer), class: "btn btn-sm btn-blue" do %>
                  Edit
                <% end %>
              </div>
              <div class="col-xs-8 mt10">
                <%= image_tag "https://s3-ap-south-1.amazonaws.com/ems.images/offers/#{offer.id}.jpg?timestamp=#{offer.updated_at.to_s}", width: '80px', id: "upload", class: "jmodal"%>

              </div>
              <div class="col-xs-4">
                <%= form_tag upload_offer_image_admin_product_offers_path(id: offer.id), class: 'form-horizontal upload_form', multipart: true do |f| %>
                  <label for="document_<%= offer.id %>" data-id="<%= offer.id %>"><%= image_tag 'upload_image.svg', width: '30px', id: "upload", class: "pointer" %></label>
                  <%= file_field_tag "document_#{offer.id}", class: 'offer_image', style:"display: none", data: {id: offer.id} %>
                <% end %>
              </div>
            </div>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
    <div class="page_links ppl">
      <%= will_paginate @offers%>
    </div>
  </div>
</div>
<script>
    ChosenApplier.init($('select[data-behavior=chosen-select]'));
    $('#product_offer_submit').on('click', function() {
        $('#product_offers_search_form').submit();
    });

    $('.offer_image').on('change', function() {
        $(this).closest('.upload_form').submit();
    });
    $('.jmodal').on('click', function() {
        let url = "<div class=\"modal fade page-body\" id=\"product_image_modal\">\n" +
            "  <div class=\"modal-dialog\">\n" +
            "    <div class=\"modal-content\">\n" +
            "      <div class=\"modal-header\">\n" +
            "        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-hidden=\"true\">×</button>\n" +
            "        <div class=\"col-xs-12 modal-body\">" +
            "      <img src='" + $(this).closest('img').first().attr("src") + "' style=\"width:100%;max-width:800px\">     </div>\n" +
            "  </div>\n" +
            "</div></div></div>";
        $(url).modal();

    });
</script>

app/views/admin/product_offers/new.html.erb
<div class="container col-md-8 page-body">
  <div class="row">
    <h4 class="col-md-2">
      <%= link_to admin_product_offers_path,  class: "btn btn-blue pull-left" do %>
        Back
      <% end %>
    </h4>
    <h4 class="col-md-8" align="center">
      Add Offer
    </h4>
  </div>
  <div class="row">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= form_for(@offer, :url => {:controller => 'product_offers', :action => 'create'}) do |f| %>
          <div class="row mrs mls new_form">
            <%= render 'form', f: f,form_type: "new" %>
          </div>
          <div class="row">
            <div class="col-md-12" align="center">
              <%= f.submit "Add", class: 'btn btn-green' %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>